// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/util/serializer/message.proto

package serializer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubSubMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PublishTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubMessage) Reset() {
	*x = PubSubMessage{}
	mi := &file_internal_util_serializer_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubMessage) ProtoMessage() {}

func (x *PubSubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_util_serializer_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubMessage.ProtoReflect.Descriptor instead.
func (*PubSubMessage) Descriptor() ([]byte, []int) {
	return file_internal_util_serializer_message_proto_rawDescGZIP(), []int{0}
}

func (x *PubSubMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PubSubMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PubSubMessage) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *PubSubMessage) GetPublishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishTime
	}
	return nil
}

func (x *PubSubMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PubSubMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_internal_util_serializer_message_proto protoreflect.FileDescriptor

const file_internal_util_serializer_message_proto_rawDesc = "" +
	"\n" +
	"&internal/util/serializer/message.proto\x12\n" +
	"serializer\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x03\n" +
	"\rPubSubMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12I\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2).serializer.PubSubMessage.AttributesEntryR\n" +
	"attributes\x12=\n" +
	"\fpublish_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishTime\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.serializer.PubSubMessage.MetadataEntryR\bmetadata\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B5Z3github.com/mehuls/gopubsub/internal/util/serializerb\x06proto3"

var (
	file_internal_util_serializer_message_proto_rawDescOnce sync.Once
	file_internal_util_serializer_message_proto_rawDescData []byte
)

func file_internal_util_serializer_message_proto_rawDescGZIP() []byte {
	file_internal_util_serializer_message_proto_rawDescOnce.Do(func() {
		file_internal_util_serializer_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_util_serializer_message_proto_rawDesc), len(file_internal_util_serializer_message_proto_rawDesc)))
	})
	return file_internal_util_serializer_message_proto_rawDescData
}

var file_internal_util_serializer_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_util_serializer_message_proto_goTypes = []any{
	(*PubSubMessage)(nil),         // 0: serializer.PubSubMessage
	nil,                           // 1: serializer.PubSubMessage.AttributesEntry
	nil,                           // 2: serializer.PubSubMessage.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_internal_util_serializer_message_proto_depIdxs = []int32{
	1, // 0: serializer.PubSubMessage.attributes:type_name -> serializer.PubSubMessage.AttributesEntry
	3, // 1: serializer.PubSubMessage.publish_time:type_name -> google.protobuf.Timestamp
	2, // 2: serializer.PubSubMessage.metadata:type_name -> serializer.PubSubMessage.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_util_serializer_message_proto_init() }
func file_internal_util_serializer_message_proto_init() {
	if File_internal_util_serializer_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_util_serializer_message_proto_rawDesc), len(file_internal_util_serializer_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_util_serializer_message_proto_goTypes,
		DependencyIndexes: file_internal_util_serializer_message_proto_depIdxs,
		MessageInfos:      file_internal_util_serializer_message_proto_msgTypes,
	}.Build()
	File_internal_util_serializer_message_proto = out.File
	file_internal_util_serializer_message_proto_goTypes = nil
	file_internal_util_serializer_message_proto_depIdxs = nil
}
